"""change_enums_to_strings_with_checks

Revision ID: 579f165f7357
Revises: 36f4d08f4e28
Create Date: 2026-04-24 22:07:54.411276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579f165f7357'
down_revision: Union[str, None] = '36f4d08f4e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.alter_column('alerts', 'trigger_method',
               existing_type=postgresql.ENUM('GESTURE', 'SHAKE', 'POWER_BUTTON', 'TIMEOUT', 'MANUAL', name='triggermethod'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('alerts', 'gesture_profile',
               existing_type=postgresql.ENUM('DEFAULT', 'HEALTHCARE', 'TEACHER', 'DELIVERY', 'CORPORATE', 'ELDERLY', name='gestureprofile'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='alertstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('fk_alerts_resolved_by', 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'ml_model_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('ml_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_alerts_resolved_by', 'alerts', 'users', ['resolved_by'], ['id'])
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='alertstatus'),
               existing_nullable=False)
    op.alter_column('alerts', 'gesture_profile',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('DEFAULT', 'HEALTHCARE', 'TEACHER', 'DELIVERY', 'CORPORATE', 'ELDERLY', name='gestureprofile'),
               existing_nullable=False)
    op.alter_column('alerts', 'trigger_method',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('GESTURE', 'SHAKE', 'POWER_BUTTON', 'TIMEOUT', 'MANUAL', name='triggermethod'),
               existing_nullable=False)
    op.drop_column('alerts', 'model_version')
    # ### end Alembic commands ###
