"""add alerts table

Revision ID: 9076cb380459
Revises: cf593753c85b
Create Date: 2026-04-23 00:57:12.960443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9076cb380459'
down_revision: Union[str, None] = 'cf593753c85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger_method', sa.Enum('GESTURE', 'SHAKE', 'POWER_BUTTON', 'TIMEOUT', 'MANUAL', name='triggermethod'), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='alertstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
