events {
    worker_connections 1024;
}

http {
    # Route for the React Website
    server {
        listen 80;

        location / {
            proxy_pass http://kg_web:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route for the Backend API
        location /api/ {
            proxy_pass http://kg_backend:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}